# Pozyskiwanie , przetwarzanie i przechowywanie danych
___

### Odczyt i zapis plikow CSV za pomoca NumPy
___
* `genfromtxt()` - pozwala na odczytywanie danych
> **Atrybuty:**
> * `fname` - (*przyjmuje lancuch znakow*); nazwa pliku lub sziezka do pliku
> * `delimiter` - (*przyjmuje lancuch znakow*); wartosc rozdzilajace lancuch znakow
> * `skip_header` - (*przyjmuje liczbe calkowita*); parametr okreslajacy liczbe wierszy, ktorze chcesz pominac na poczatki pliku

* `savetxt()` - pozwala zapisac dane do pliku

##### Oczyt pliku za pomoca funkcji `genfromtxt ()`

In [16]:
#importuje funkjce genfromtxt
from numpy import genfromtxt

#odczytuje plik csv
product_data = genfromtxt('data/csv/demo.csv', delimiter = ',')
print(product_data)

[[14. 32. 33.]
 [24. 45. 26.]
 [27. 38. 39.]]


##### Zapis pliku za pomoca funkcji `savetxt()`

In [15]:
import numpy as np

#tworze przykladowe dane
sample_array = np.array([ [3,4,5], [6,7,8,], [9,10,11] ])

#zapisuje dane
np.savetxt("data/csv/my_first_demo.csv",sample_array, delimiter= ',')

### Odczyt i zapis plikow CSV za pomoca Pandas
___
* `read_csv()`- sluzy do odczyty plikow csv
> **Atrybuty:**
> * `filepath_or_buffer` - sciezka odczytywanego pliku lub jego adres URL
> * `sep` - wyznacza sepataror w lancuchu znakow. Domyslnym jest ','
> * `header` - sluzy do rozpoznawania nazw kolumn. Domyslna wartosc infer
> * `names` - moge tu wprowadzic liste nazw kolumn. Domyslna wartosc None
* `to_csv()`- sluzy do zapisu plika csv
> **Atrybuty:**
> * `path_or_buf` - sciezka pliku lub lokacje dok ktroteg plik bedzie eksportowany
> * `sep` - separator plikow wejscowych
> * `header` - pozwala umieszczac nazwy kolumn. Domyslna wartosc True
> * `index` - zapisuje indeks do pliku. Domyslna wartosc True

##### Oczyt pliku za pomoca funkcji `pd.read_csv ()`

In [36]:
import pandas as pd

sample_df = pd.read_csv('data/csv/demo.csv', sep = ',', header = None)
sample_df.head()

0   1   2
0  14  32  33
1  24  45  26
2  27  38  39

##### Zapis pliku za pomoca funkcji  `to_csv()`

In [26]:
# Zapisuje obiekt DataFrame w pliku csv
sample_df.to_csv('data/csv/demo_sample_df.csv')

### Odczyt i zapis plikow arkusz kalkulacyjnego Excel
____
* `pd.read_exce()` - sluzy do otrzytania odczytania Excela 
* `df.to_excel()`- sluzy do zapisywanie pliku do Excela
> Atrybut:
> `sheet_name()`- nazwa akrusza

 ##### Oczyt pliku za pomoca funkcji `pd.read_excel()`

In [33]:
import pandas as pd

df = pd.read_excel('data/excel/employee.xlsx', sheet_name = 'performance')
df.head()

name  performance_score
0    Allen Smith                723
1        S Kumar                520
2    Jack Morgan                674
3      Ying Chin                556
4  Dheeraj Patel                711

##### Zapis pliku za pomoca funkcji  `to_excel()`

In [37]:
df.to_excel('data/excel/employee_performance.xlsx')

##### Mozemy takze zapisac wieksza liczbe obiektow DataFrame w jednym pliku Excela (kazda ramka danych w osobobym akruszu) za pomoca funkcji `with pd.ExcelWriter("file") as writer:`

In [50]:
emp_df = pd.read_excel('data/excel/employee.xlsx', sheet_name = 'employee_details')
emp_df.head()

with pd.ExcelWriter('data/excel/new_employee_details.xlsx') as writer:
    emp_df.to_excel(writer,sheet_name = 'employee')
    df.to_excel(writer, sheet_name = 'performance')