In [1]:
import numpy as np

In [8]:
# Tworzenie tablicy 
a = np.array([1,2,3,4,5], dtype = float) # wszystkie elementy tablicy takiego samego typu danych, "dtype" - wyznaczna typ tablicy 
a

array([1., 2., 3., 4., 5.])

In [14]:
# Tworzenie tablicy za pomoca funckji arange(), funkcja otrzymuje trzy argumenty start, stop, step (SSS)
a = np.arange(10,100,10) # defolt start = 0 , step = 1
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
# Funkcja zeros() - tworzy wypelniona zerami tablice o okreslonych wartosciach
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [18]:
# Funkcja ones () - tworzy wypelniona jedynkami tablice o okreslonych wartosciach
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [30]:
# Funkcja full() - tworzy wypelniona zerami tablice o okreslonych wartosciach
a = np.full((2,3),4) 
a

array([[4, 4, 4],
       [4, 4, 4]])

In [33]:
# Funkcja eye() - tworzy macierz jednostkowa
a = np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# Funkcja random.random() - tworzy macierz wypelniona losowymi wartosciami
a = np.random.random((2,3))
a

array([[0.07668848, 0.81853431, 0.35156761],
       [0.11007516, 0.02171855, 0.88520961]])

In [50]:
wek = np.array([1, 2, 3, 4, 5])
wek.shape # zwraca wymiary wygerowangego wektora


(5,)

# Kody znakowe typow danych
    staloprzecinkowy  - i
    bezznakowy staloprzecinkowy - u
    logiczny - b
    liczby zespolone - D
    lancuch znakow - S
    zmiennoprzecinkowe pojedynczej precyzji - f
    zmiennoprzecinkowe podwojnej precycji - d 

In [73]:
# Przyklad uzycia :
a = np.arange(1,10, dtype = "f") # tworzy tablice Numpy z zmiennoprzecinkowymi liczbani
b = np.arange(1,10, dtype = "D") # tworzy tablcie Numpy z liczbami zespolonymi
a
b

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j,
       9.+0.j])

# Manipulowanie wymiarami tablic

In [83]:
# Funkcja reshape() zmienia wymiary tablic

arr = np.arange(1,13) 
new_arr = arr.reshape(3,4)
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [2]:
# Funkcja flatten i revel () - przeksztalca macierz n-wymierarowa w macierz jednowymiarowa
# Fukcja ravel - tez jak i flatten () - przeksztalca macierz n-wymierarowa w macierz jednowymiarowa, 
# ale jest szybciej od funkcji flatten () tak jak , zwraca odniesienie do pierwotnej tablicy a nie zwraca rzecywista tablice
# jak to robi flatten()


arr = np.arange(15).reshape(3,5)
arr.flatten()
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
# Funkcja transpose(), metoda .T - transponuje daną macierze czyli zamienia rzędy macierzy z kolumnami
arr = np.arange(1,13).reshape(3,4)
arr
arr.T
arr.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [37]:
# Funckja resize() - zmienia rozmiar tablicy Numpy
arr.reshape(2,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

# Łączenie tablic Numpy
 
 ##### Biblioteka numpy umożliwia łączenie tablic wzdłuż wybranej osi. Mozemy je właczyć :
     
    1. w poziomie - np.hstack((arr1,arr2)), np.concatenate((arr1,arr2),axis = 1)
    2. w pionie  -  np.vstack((arr1,arr2)), np.concatenate((arr1,arr2),axis = 0)
    3. po kolumnach ( czyli jak z n k-wymiarowych wektorow zrobic tablice) - np.column_stack((arr1,arr2))
    4. po rzędach - np.row_stack((arr1,arr2))
    5. w głąb  - np.dstack((arr1,arr2))
  

In [43]:
# Łączenie w poziomie 
arr1 = np.arange(1,10).reshape(3,3)
arr2 = arr1* 2
arr3 = np.hstack((arr1,arr2)) 
arr4 = np.concatenate((arr1,arr2), axis = 1)
arr4

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [41]:
#Łączenie w pionie
arr3 = np.vstack((arr1,arr2)) 
arr4 = np.concatenate((arr1,arr2), axis = 1)
arr4

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [45]:
#Łączenie w głąb
arr3 = np.dstack((arr1,arr2))
arr3

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])

In [50]:
#Łączenie po kolumhach
arr1 = np.arange(1,5)
arr2 = arr1 * 2
arr3 = np.column_stack((arr1,arr2))
arr3

array([[1, 2],
       [2, 4],
       [3, 6],
       [4, 8]])

In [53]:
#Łączenie po rzędach
arr4 = arr1 * 4
arr3  = np.row_stack((arr1,arr2,arr4))
arr3

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 4,  8, 12, 16]])

# Rozdzielanie tablic Numpy
  
  * podział w poziomie - **hsplit(arr, liczba na ile podtablic dzielimy tablice)**
  * podział w pionie  - **vsplit(arr, liczba na ile podtablic dzielimy tablice)**
   
  *lub wykorzustujemy uniwerslaną funkcje **split(arr,liczba na ile podtablic dzielimy tablice, axis = 0/ver,1/hor)**

In [66]:
#Podział w poziomie
arr = np.arange(1,10).reshape(3,3)
arr
split_arr = np.hsplit(arr,3)
split_arr

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [63]:
# Podział w pionie#
split_arr = np.vsplit(arr,3)
split_arr[1]

array([[4, 5, 6]])

# Zmiana typu danych tablic Numpy
Funkcja **astype()** przekształca typ danych określonej tablicy

In [73]:
arr = np.arange(1,10).reshape(3,3)
print("Tablica (typ danych int):", arr)
arr = arr.astype(float)
print("Zmieniony typ danych tablicy z int na float:", arr)

Tablica (typ danych int): [[1 2 3]
 [4 5 6]
 [7 8 9]]
Zmieniony typ danych tablicy z int na float: [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
# funkjca tolist()  przeksztalca tablice Numpy na liste Pythona

In [81]:
arr = np.arange(1,13)
arr
list1 = arr.tolist()
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

# Tworzenie widokow i kopii Numpy
Niektore funkcje Pythona zwracaja kopie lub widok tablicz wejsciowej.Kopia przechowuje tablice w innym miejscu , natomiast widok wykorzystuje ten sam obszar pamieci co tablica. 
Cehcy kopii i widokow:
* modyfikacje widoku wplywaja na przechowywane dane, natomiast modyfikacje kopii nie maja wplywu na pierwotna tablice
* widoki korzystuja z pamieci wspoluzytkowanej
* kopie wymagaja wiecej pamieci w porownaniu do widokow
* kopie dzialaja wolnej do widokow

In [92]:
arr = np.arange(1,5).reshape(2,2)

#Przypisanie (nie kopia)
arr_not_copy = arr


#Tworzymy kopię głęboką
arr_copy = arr.copy()


#Tworzymy kopie za pomoca widoku
arr_view = arr.view()

print("Pierwotna tablica : " ,id(arr))
print("Przypisanie : " , id(arr_not_copy))
print("Kopia gleboka: " , id(arr_copy))
print("Widok : ", id(arr_view))

#Pierwotna tablica i przypisana tablcia maja taki sam id co oznacza ze wskazuja na ten sam objekt.
#Kopia i widom  maja inne id , sa nowymi objektami, ale objekt widoku odnoszi sie do piewotnej tablica,
# a kopia dysponuje osobna replike tej tablicy 

Pierwotna tablica :  2289200965552
Przypisanie :  2289200965552
Kopia gleboka:  2289201164624
Widok :  2289201166448


# Fragmentowanie tablic Numpy 

In [104]:
arr = np.arange(0,10)
arr[3:6] # [pierwszy element wlacznie , do drugiego nie wlacznie]
arr[2:7:2] # od 2 do 7 nie wlacznie , ze skokiem 2

array([2, 4, 6])

 # Indeksowanie logiczne i indeksowanie specjalne
 **(boolean indexing and fancy indexing)** wybieranie i filtrowanie elementow w tablice


In [3]:
# Boolean indexing
arr = np.arange(21,41,2)
arr[arr>30] 

# Fancy indexing
arr = np.arange(1,21).reshape(5,4)
arr
indices = [1,2] # wybrano drugi i trzeci rzed
arr[indices]
indices = [2,3] # wybrano treci i czwarty rzed
arr[indices]
row = np.array([1,2])
col = np.array([2,3])
arr[row,col]

array([ 7, 12])