In [1]:
import numpy as np

In [8]:
# Tworzenie tablicy 
a = np.array([1,2,3,4,5], dtype = float) # wszystkie elementy tablicy takiego samego typu danych, "dtype" - wyznaczna typ tablicy 
a

array([1., 2., 3., 4., 5.])

In [14]:
# Tworzenie tablicy za pomoca funckji arange(), funkcja otrzymuje trzy argumenty start, stop, step (SSS)
a = np.arange(10,100,10) # defolt start = 0 , step = 1
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
# Funkcja zeros() - tworzy wypelniona zerami tablice o okreslonych wartosciach
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [18]:
# Funkcja ones () - tworzy wypelniona jedynkami tablice o okreslonych wartosciach
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [30]:
# Funkcja full() - tworzy wypelniona zerami tablice o okreslonych wartosciach
a = np.full((2,3),4) 
a

array([[4, 4, 4],
       [4, 4, 4]])

In [33]:
# Funkcja eye() - tworzy macierz jednostkowa
a = np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# Funkcja random.random() - tworzy macierz wypelniona losowymi wartosciami
a = np.random.random((2,3))
a

array([[0.07668848, 0.81853431, 0.35156761],
       [0.11007516, 0.02171855, 0.88520961]])

In [50]:
wek = np.array([1, 2, 3, 4, 5])
wek.shape # zwraca wymiary wygerowangego wektora


(5,)

# Kody znakowe typow danych
    staloprzecinkowy  - i
    bezznakowy staloprzecinkowy - u
    logiczny - b
    liczby zespolone - D
    lancuch znakow - S
    zmiennoprzecinkowe pojedynczej precyzji - f
    zmiennoprzecinkowe podwojnej precycji - d 

In [73]:
# Przyklad uzycia :
a = np.arange(1,10, dtype = "f") # tworzy tablice Numpy z zmiennoprzecinkowymi liczbani
b = np.arange(1,10, dtype = "D") # tworzy tablcie Numpy z liczbami zespolonymi
a
b

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j,
       9.+0.j])

# Manipulowanie wymiarami tablic

In [83]:
# Funkcja reshape() zmienia wymiary tablic

arr = np.arange(1,13) 
new_arr = arr.reshape(3,4)
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
# Funkcja flatten i revel () - przeksztalca macierz n-wymierarowa w macierz jednowymiarowa
# Fukcja ravel - tez jak i flatten () - przeksztalca macierz n-wymierarowa w macierz jednowymiarowa, 
# ale jest szybciej od funkcji flatten () tak jak , zwraca odniesienie do pierwotnej tablicy a nie zwraca rzecywista tablice
# jak to robi flatten()


arr = np.arange(15).reshape(3,5)
arr.flatten()
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])